# vim: set tabstop=2 shiftwidth=2 expandtab:

# DOCS: https://docs.github.com/en/pages/
# DOSS: https://github.com/pages-themes/architect
# DOSS: https://github.com/jekyll/minima

theme: jekyll-theme-architect
title: Sapere Aude
